(SIMP-3463) Add EL8 support
simp/simp-selinux-policy pull request #2
Opened 2020-10-08 18:03 UTC by trevor-vaughan

- Added EL8 support
- Changed the base release to 1 to align with the Fedora packaging guidelines

SIMP-3463 #close

2020-10-13 13:32 UTC, lnemsick-simp commented on build/simp-selinux-policy.spec
> +      %global policycoreutils_version 2.8.16
In CentOS-8-x86_64-1904-dvd1.iso, the policycore_utils package is named policcoreutils-2.8-16.1.

2020-10-13 13:33 UTC, lnemsick-simp requested changes
Version mismatch

2020-10-15 22:49 UTC, op-ct commented on build/simp-selinux-policy.spec
> +      %global selinux_policy_version 3.14.1
Which EL8 release should this target? On `CentOS-8.2.2004-x86_64-dvd1.iso`, the `policycoreutils` package is 2.9-9 and the `selinux-policy` package is 3.14.3-41.

2020-10-16 16:18 UTC, jeannegreulich commented on build/simp-selinux-policy.spec
> +      %global selinux_policy_version 3.14.1
It says in the documentation that it targets the earliest version of a release

2020-10-16 16:39 UTC, lnemsick-simp commented on build/simp-selinux-policy.spec
> +      %global selinux_policy_version 3.14.1
Is there a reason to have the release qualifier (16.1) on the version?

2020-10-16 19:38 UTC, jeannegreulich approved these changes

2020-10-16 19:42 UTC, merged